services:
  valhalla-init:
    image: ghcr.io/valhalla/valhalla:latest
    volumes:
      - ./valhalla_data:/data
    entrypoint: >
      bash -c "
        set -e;
        cd /data;
        if [ ! -f ${PBF_FILE} ]; then
          echo '[init] Downloading PBF file...';
          wget -O ${PBF_FILE} ${PBF_URL};
        else
          echo '[init] PBF file already exists, skipping download.';
         if [ ! -f valhalla.json.sha256 ] || ! sha256sum -c valhalla.json.sha256 > /dev/null 2>&1; then
          echo '[init] Generating config...';
          valhalla_build_config > /data/valhalla.json;
          valhalla_build_timezones > /data/timezones.sqlite;
          echo '[init] Building tiles...';
          valhalla_build_tiles -c /data/valhalla.json /data/${PBF_FILE};
          tar -cvf tiles.tar valhalla
          mv tiles.tar valhalla
          sha256sum valhalla.json > valhalla.json.sha256;
          echo '[init] Done.';
        else
          echo '[init] Config already exists, skipping.';
        fi
      "
    depends_on: []
    restart: "no"

  valhalla:
    image: ghcr.io/valhalla/valhalla:latest
    container_name: valhalla
    ports:
      - "8002:8002"
    volumes:
      - ./valhalla_data:/data
    environment:
      - VALHALLA_CONF=/data/valhalla.json
    command: valhalla_service /data/valhalla.json
    depends_on:
      - valhalla-init
    restart: unless-stopped